### ISSUE TITLE
Crash to Desktop from java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by uberpudge** [feldim2425/MoreOverlays#80]
I was in the overworld at my base.  
I pressed F7 to turn on the spawnable surface overlay and the game crashed to Desktop.  
Error received in log:  
```
java.lang.NoSuchMethodError: com.mojang.blaze3d.platform.GlStateManager.pushMatrix()V
	at at.feldim2425.moreoverlays.lightoverlay.LightOverlayRenderer.renderOverlays(LightOverlayRenderer.java:29)
	at at.feldim2425.moreoverlays.lightoverlay.LightOverlayHandler.renderWorldLastEvent(LightOverlayHandler.java:54)
...
```

Minecraft version: `1.15.2`  
Forge version (from logs):  
```
--fml.forgeVersion 31.2.0
--fml.mcVersion 1.15.2
--fml.mcpVersion 20200515.085601
```
Mods installed:  
```
Mods:
  [✔️] Advanced-XRay-Mod-1.15.2
  [✔️] jei-1.15.2-6.0.0.4
  [✔️] journeymap-1.15.2-5.7.0beta1
  [✔️] moreoverlays-1.16.1
```

[Link to full logs with crash report](https://pastebin.com/A9cG2eg).  
Crash report starts on L201.  

[Link to source file and line that caused the crash](https://github.com/feldim2425/MoreOverlays/blob/master-1.14/src/main/java/at/feldim2425/moreoverlays/lightoverlay/LightOverlayRenderer.java#L29).  

...and I just realized that link is on the master branch for `1.14`.  
`master` has a different import for `GLStateManager`:
```java
import net.minecraft.client.renderer.GlStateManager;
```
whereas `1.14` imports it from:  
```java
import com.mojang.blaze3d.platform.GlStateManager;
```

The mod version from the logs is `1.16.1`.  
I suppose now I'm wondering why the mod I installed uses the `1.14` code base if the version is `1.16.1`?  

I downloaded this from [Curseforge](https://www.curseforge.com/minecraft/mc-mods/more-overlays) using [this link for the specific file](https://www.curseforge.com/minecraft/mc-mods/more-overlays/files/2829171).  

Do they have the version wrong?  
Is there a better link to use for the correct version?

**Comment by r8420** [comment]
There is no official support for 1.15.2 yet. I made some changes and got it to work on 1.15.2. You can download it here:
[https://github.com/r8420/MoreOverlays-1.15/releases](https://github.com/r8420/MoreOverlays-1.15/releases)
Edit: now also available on Curse: [Here](https://www.curseforge.com/minecraft/mc-mods/more-overlays-updated)
